#!/usr/bin/env bash
# Post-generate setup: local.properties (Android SDK) + git init + first commit.
# Usage: setup.sh <projectDir>
set -euo pipefail

DIR="${1:?project dir required}"
cd "$DIR"

# 1. local.properties → sdk.dir
SDK="${ANDROID_HOME:-${ANDROID_SDK_ROOT:-$HOME/Library/Android/sdk}}"
if [ -d "$SDK" ]; then
  if [ ! -f local.properties ] || ! grep -q '^sdk.dir=' local.properties 2>/dev/null; then
    printf 'sdk.dir=%s\n' "$SDK" >> local.properties
    echo "  local.properties -> sdk.dir=$SDK"
  else
    echo "  local.properties: sdk.dir already set"
  fi
else
  echo "  WARN: Android SDK not found at $SDK — local.properties skipped"
fi

# 2. git init + initial commit
if [ ! -d .git ]; then
  git init -q
  git add -A
  NAME="$(git config user.name 2>/dev/null || echo cmpose)"
  EMAIL="$(git config user.email 2>/dev/null || echo noreply@cmpose.dev)"
  git -c user.name="$NAME" -c user.email="$EMAIL" \
      commit -q -m "Initial commit (generated by cmpose.dev)"
  echo "  git: initialized + initial commit"
else
  echo "  git: already a repository — skipped"
fi
